#!/bin/sh
# docker-entrypoint.sh
# Injects runtime environment variables into the built SPA at container startup.
# This allows the same Docker image to be deployed to multiple environments
# without rebuilding.

set -e

ENV_JS_FILE="/usr/share/nginx/html/env-config.js"

echo "🔧 Injecting runtime environment variables..."

cat > "$ENV_JS_FILE" << EOF
// Auto-generated by docker-entrypoint.sh — DO NOT EDIT
window.__ENV__ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-}",
  VITE_APP_VERSION: "${VITE_APP_VERSION:-unknown}",
  VITE_FEATURE_FLAGS: "${VITE_FEATURE_FLAGS:-}",
  VITE_SENTRY_DSN: "${VITE_SENTRY_DSN:-}",
  VITE_GA_TRACKING_ID: "${VITE_GA_TRACKING_ID:-}"
};
EOF

echo "✅ Environment config written to $ENV_JS_FILE"
echo "   VITE_API_BASE_URL=${VITE_API_BASE_URL:-<not set>}"
echo "   VITE_APP_VERSION=${VITE_APP_VERSION:-<not set>}"

# Start the main process
exec "$@"
